# pytest config
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -v --cov=src"
testpaths = ["tests"]
console_output_style = "progress"
pythonpath = "src"

# log configs
log_cli = true
log_cli_level = "WARNING"
log_format = "%(asctime)s - %(levelname)s - %(message)s"
log_date_format = "%d-%m-%Y %H:%M:%S"
norecursedirs = ["data", "examples"]

# specify cache directory for pytest cache
cache_dir = ".pytest_cache"

# pytest-cov config
[tool.coverage.run]
omit = [
    "src/*_simulation.py",
    "*/data/*",
    "*/examples/*"
]

# pytest-cov config
[tool.coverage.report]
show_missing = "true"
