services:
  default_simulation:
    build:
      context: ..
    image: simulations
    container_name: dafault_simulation
    tty: true
    command: python src/default_simulation.py
    volumes:
      - ./src/data/default_simulation/:/app/src/data/default_simulation
