# Swap constants
ENTANGLEMENT_SWAPPING_PROB: float = 0.9
SWAP_DEGRADATION: float = 0.99

# Entanglement Constants
ENTANGLEMENT_FIDELITY: float = 0.9

# Memory Constants
MEMORY_ARRAY_SIZE: int = 10
MEMORY_ARRAY_NAME: str = ".MemoryArray"
MEMORY_FIDELITY: float = 0.9
MEMORY_FREQUENCY: int = 2000
MEMORY_EFFICIENCY: float = 1
MEMORY_COHERENCE_TIME: int = -1
MEMORY_WAVELENGTH: int = 500

# Bsm constants
BSM_EFFICIENCY: int = 1

# Channels constants
QCHANNEL_DISTANCE: int = 1_000
QCHANNEL_ATTENUATION: int = 0
CCHANNEL_DISTANCE: int = 1_000
CCHANNEL_DELAY: int = 100_000_000 # 1e8